import { house1, house2, house3 } from '../assets';
import currencyData from './world_currency_symbols.json';

export const altHouses = [
  {
    id: 1,
    shared: true,
    location: { city: 'Kasarani', state: 'Nairobi', country: 'Kenya' },
    price: 13000,
    images: [house1, house2, house3],
    coverImage: house1,
    numRooms: 3,
    numBathrooms: 2,
    address: '112, Carwash, Zimmerman',
    name: 'Twiga House',
    houseType: 'Apartment',
    floor: 4,
  },
  {
    id: 2,
    shared: false,
    location: { city: 'Njiru', state: 'Nairobi', country: 'Kenya' },
    price: 10000,
    images: [],
    coverImage: house2,
    numRooms: 1,
    numBathrooms: 1,
    address: '1023, Mowlem, Saika',
    name: 'Mowlem Heights',
    houseType: 'Apartment',
  },
  {
    id: 3,
    shared: false,
    location: { city: 'Umoja', state: 'Nairobi', country: 'Kenya' },
    price: 30000,
    images: [],
    coverImage: house3,
    numRooms: 3,
    numBathrooms: 2,
    address: '12, Komarock, Embakasi Central',
    name: "Nyambura's",
    houseType: 'Bungalow',
  },
  {
    id: 4,
    shared: true,
    location: { city: 'Kasarani', state: 'Nairobi', country: 'Kenya' },
    price: 13000,
    images: [],
    coverImage: house1,
    numRooms: 3,
    numBathrooms: 2,
    address: '112, Carwash, Zimmerman',
    name: 'Twiga House',
    houseType: 'Apartment',
  },
  {
    id: 5,
    shared: false,
    location: { city: 'Njiru', state: 'Nairobi', country: 'Kenya' },
    price: 10000,
    images: [],
    coverImage: house2,
    numRooms: 1,
    numBathrooms: 1,
    address: '1023, Mowlem, Saika',
    name: 'Mowlem Heights',
    houseType: 'Apartment',
  },
  {
    id: 6,
    shared: false,
    location: { city: 'Umoja', state: 'Nairobi', country: 'Kenya' },
    price: 30000,
    images: [],
    coverImage: house3,
    numRooms: 3,
    numBathrooms: 2,
    address: '12, Komarock, Embakasi Central',
    name: "Nyambura's",
    houseType: 'Bungalow',
  },
];

export const rootUrl = 'http://localhost:5000/api/v1';

export const currency = currencyData;
